"""add user provider and roll_number

Revision ID: 700f2361a1c6
Revises: 
Create Date: 2026-02-14 17:16:41.135652
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '700f2361a1c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('roll_number', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('provider', sa.String(length=20), nullable=False, server_default='LOCAL'))
    op.create_index('uq_users_roll_number', 'users', ['roll_number'], unique=True)
    op.add_column('attendance_sessions', sa.Column('qr_expires_at', sa.DateTime(), nullable=True))
    op.add_column('attendance_sessions', sa.Column('attendance_code', sa.String(length=10), nullable=True))
    op.add_column('attendance_sessions', sa.Column('code_expires_at', sa.DateTime(), nullable=True))
    op.add_column('attendance_sessions', sa.Column('face_recognition_enabled', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_attendance_sessions_attendance_code'), 'attendance_sessions', ['attendance_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendance_sessions_attendance_code'), table_name='attendance_sessions')
    op.drop_column('attendance_sessions', 'face_recognition_enabled')
    op.drop_column('attendance_sessions', 'code_expires_at')
    op.drop_column('attendance_sessions', 'attendance_code')
    op.drop_column('attendance_sessions', 'qr_expires_at')
    op.drop_index('uq_users_roll_number', table_name='users')
    op.drop_column('users', 'provider')
    op.drop_column('users', 'roll_number')
    # ### end Alembic commands ###
