from fastapi import FastAPI, UploadFile, Form, File, Request
from fastapi.responses import HTMLResponse
from fastapi.templating import Jinja2Templates
from sqlalchemy.orm import Session
import uvicorn
from database import Base, engine, SessionLocal
from models import Person
from face_encoder import FaceEncoder
import numpy as np
import pickle
import uuid
import os
import cv2
import base64
from datetime import datetime

app = FastAPI()
Base.metadata.create_all(bind=engine)
templates = Jinja2Templates(directory="templates")
encoder = None
EMBEDDINGS_MASTER_PATH = os.path.join("embeddings", "all_embeddings.pkl")


@app.middleware("http")
async def log_requests(request: Request, call_next):
    print(f"\n📨 FaceModel incoming request: {request.method} {request.url.path}", flush=True)
    response = await call_next(request)
    print(f"📤 FaceModel response: {response.status_code} {request.method} {request.url.path}", flush=True)
    return response


def load_known_embeddings() -> tuple[np.ndarray, list[str]]:
    """Load known embeddings from PKL (preferred) or DB fallback."""
    # Preferred source: embeddings generated by generate_embeddings.py
    if os.path.exists(EMBEDDINGS_MASTER_PATH):
        with open(EMBEDDINGS_MASTER_PATH, "rb") as f:
            all_embeddings = pickle.load(f)

        known_names = list(all_embeddings.keys())
        known_embeddings = np.array([all_embeddings[name] for name in known_names])
        return known_embeddings, known_names

    # Fallback source: legacy DB records
    db: Session = SessionLocal()
    persons = db.query(Person).all()
    known_embeddings = []
    known_names = []

    for p in persons:
        emb = pickle.loads(p.embedding)
        known_embeddings.append(emb)
        known_names.append(p.name)
    db.close()

    return (np.array(known_embeddings) if known_embeddings else np.array([]), known_names)


def get_encoder() -> FaceEncoder:
    global encoder
    if encoder is None:
        try:
            print("🤖 Initializing FaceEncoder...", flush=True)
            encoder = FaceEncoder()
            print("✅ FaceEncoder initialized successfully", flush=True)
        except Exception as e:
            print(f"❌ Failed to initialize FaceEncoder: {e}", flush=True)
            raise
    return encoder

@app.get("/", response_class=HTMLResponse)
async def home(request: Request):
    return templates.TemplateResponse("train.html", context={"request": request})
@app.post("/train/")
async def train_person(
    person_id: int = Form(...),
    name: str = Form(...),
    files: list[UploadFile] = File(...)
):
    db: Session = SessionLocal()
    
    embeddings = []

    for file in files:
        contents = await file.read()
        emb = get_encoder().encode_image(contents)
        if emb is not None:
            embeddings.append(emb)

    if not embeddings:
        return {"error": f"No valid faces found for {name}"}

    avg_embedding = np.mean(embeddings, axis=0)
    serialized = pickle.dumps(avg_embedding)

    person = Person(id=person_id, name=name, embedding=serialized)
    db.merge(person)  # upsert
    db.commit()
    db.close()

    return {"message": f"✅ {name} (ID={person_id}) trained successfully!"}

@app.get("/recognize-page", response_class=HTMLResponse)
async def recognize_page(request: Request):
    return templates.TemplateResponse("recognize.html", context={"request": request})

@app.post("/recognize")
@app.post("/recognize/")
async def recognize_faces(file: UploadFile = File(...)):
    print("\n📥 FaceModel /recognize request received", flush=True)
    print(f"   filename: {file.filename}", flush=True)
    
    try:
        contents = await file.read()
        print(f"   bytes_received: {len(contents)}", flush=True)
        npimg = np.frombuffer(contents, np.uint8)
        img = cv2.imdecode(npimg, cv2.IMREAD_COLOR)

        if img is None:
            print("   ❌ FaceModel could not decode image", flush=True)
            return {
                "success": False,
                "faces_detected": 0,
                "recognized_faces": [],
                "recognized_names": [],
                "unknown_faces": [],
                "results": [],
                "image_with_boxes": None,
                "timestamp": datetime.now().isoformat(),
                "error": "Invalid image file",
            }

        print("   📊 Loading known embeddings...", flush=True)
        known_embeddings, known_names = load_known_embeddings()
        print(f"   ✅ Loaded {len(known_names)} known embeddings", flush=True)

        # Detect faces in the uploaded image
        print("   🔍 Detecting faces...", flush=True)
        faces = get_encoder().detect_faces(img)
        print(f"   ✅ Detected {len(faces)} faces", flush=True)
        
        threshold_cos = 0.4  # tweak for sensitivity

        results = []
        recognized_faces = []
        unknown_faces = []

        for face in faces:
            emb = get_encoder().l2_normalize(face.embedding)
            name = "Unknown"
            confidence = 0.0

            if known_embeddings.size > 0:
                cos_sim = np.dot(known_embeddings, emb)
                idx = int(np.argmax(cos_sim))
                max_sim = float(cos_sim[idx])

                confidence = max_sim
                if max_sim > threshold_cos:
                    name = known_names[idx]

            print(f"   face_result: name={name}, confidence={confidence:.3f}", flush=True)

            x1, y1, x2, y2 = map(int, face.bbox)
            w = x2 - x1
            h = y2 - y1

            face_result = {
                "name": name,
                "confidence": confidence,
                "bbox": [x1, y1, w, h],
            }
            results.append(face_result)

            if name == "Unknown":
                unknown_faces.append(face_result)
            else:
                recognized_faces.append(face_result)

            cv2.rectangle(img, (x1, y1), (x2, y2), (0, 255, 0), 2)
            cv2.putText(img, f"{name} ({confidence:.2%})", (x1, y1 - 10),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.8, (0, 255, 0), 2)

        recognized_names = []
        for r in recognized_faces:
            nm = r["name"]
            if nm not in recognized_names:
                recognized_names.append(nm)

        print(f"   recognized_names: {recognized_names}", flush=True)
        print(f"   unknown_faces: {len(unknown_faces)}", flush=True)

        _, buffer = cv2.imencode('.jpg', img)
        image_base64 = base64.b64encode(buffer).decode('utf-8')

        return {
            "success": True,
            "faces_detected": len(results),
            "recognized_faces": recognized_faces,
            "recognized_names": recognized_names,
            "unknown_faces": unknown_faces,
            "results": results,
            "image_with_boxes": image_base64,
            "timestamp": datetime.now().isoformat(),
        }
    
    except Exception as e:
        print(f"   ❌ Error processing image: {str(e)}", flush=True)
        import traceback
        traceback.print_exc()
        return {
            "success": False,
            "faces_detected": 0,
            "recognized_faces": [],
            "recognized_names": [],
            "unknown_faces": [],
            "results": [],
            "image_with_boxes": None,
            "timestamp": datetime.now().isoformat(),
            "error": f"Face recognition error: {str(e)}",
        }


if __name__ == "__main__":
    host = os.getenv("HOST", "127.0.0.1")
    port = int(os.getenv("PORT", "8002"))
    uvicorn.run(app, host=host, port=port)